### ISSUE TITLE
Black screen after finishing a song

### ISSUE THREAD

**Issue by GuiIIe** [notchxu/osu-to-etterna#2]
When I finish a score and then get out of the score screen my screen keeps in black and I cant do anything. If  I want to play again, I have to re open the game.

**Comment by n44a** [comment]
I don't know if you have already found a solution, I hope so.
But if not, I discovered something similar. It doesn't fix the bug but it makes things easier.
Simply when finishing a score press the "retry" button on the keyboard ("º" this button, below the "esc") and then exit normally from the beginning of the song.
It seems that on that black screen there is a bug on the final score screen.
I think it is a bug in some graphics option, since the same thing happened to me when I left in the middle of the song and I fixed that by lowering the resolution

**Comment by GuiIIe** [comment]
Hello, since this happened a year ago I cant remember too well how I fixed it. But from what I can remember the problem was the etterna version, I just had to update it. Also, I dont think this solution would work becasue if you press the retry button you would lose the score that you did.
